### ISSUE TITLE
gender 识别对于多人识别上有什么限制吗？

### ISSUE THREAD

**Issue by archersmind** [vipstone/faceai#12]
你好，使用如下图片尝试了 gender.py，处理之后的图片没有任何变化。 AI 初学者，请教下可能是什么原因？
![gather](https://user-images.githubusercontent.com/1461331/41508073-19817338-7271-11e8-9823-edfb35c29453.jpg)

**Comment by vipstone** [comment]
脸部识别有一个最小尺寸设置minSize属性，根据你的需求设置一下图片尺寸，应该就好了.
