### ISSUE TITLE
another language

### ISSUE THREAD

**Issue by candidodmv** [vipstone/faceai#13]
Congrats for this amazing project, but would be very useful if there is a version in english because this is the language of the world. Thanks

**Comment by vipstone** [comment]
Thanks for your advice.Because my English is poor, Welcome everyone to upload the English version.Thank you.

**Comment by archersmind** [comment]
Let me have a try. @vipstone 
I can upload English version and send PR when I'm free.

**Comment by vipstone** [comment]
@archersmind Thank you very much.

**Comment by archersmind** [comment]
@vipstone  One more thing, In the future we should also using English in our comments of git logs.

**Comment by candidodmv** [comment]
thanks @archersmind  if I did know chinese(I think that is the language is used in this repo), I'm also could help you with translation.
