### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by AIprogrammer** [vipstone/faceai#30]
Traceback (most recent call last):
  File "face_recog.py", line 15, in <module>
    face_recognition.load_image_file(path + "/" + fn))[0])
IndexError: list index out of range
[ WARN:0] terminating async callback

请问这里是哪里出了问题吗？文件夹里面放了两张图片可以运行，但是增加图片之后报错，始终找不到问题，为什么list[0]错误呢？

**Comment by zcgecho** [comment]
图片的问题。建议换一张图片。

**Comment by McDingl** [comment]
把报错的行改为：

known_face_encodings = face_recognition.face_encodings(face_recognition.load_image_file(path + "/" + fn))
if len(known_face_encodings) > 0:
       total_face_encoding.append(known_face_encodings[0])

解析可以参考：https://github.com/ageitgey/face_recognition/wiki/Common-Errors#list-index-out-of-range-errors
