### ISSUE TITLE
你好，我使用多人脸图片只能检测出一张人脸

### ISSUE THREAD

**Issue by SunHu1** [vipstone/faceai#38]
谢谢你的项目分享，你能给我点帮助么？还是源码需要进行一点修改才能准确的检测到多张人脸

**Comment by edward4396** [comment]
![1](https://user-images.githubusercontent.com/32833890/62184468-cb5c5800-b390-11e9-8014-88d139e95824.png)

**Comment by edward4396** [comment]
![1](https://user-images.githubusercontent.com/32833890/62184485-edee7100-b390-11e9-9949-9edc36c72f0c.png)

**Comment by SunHu1** [comment]
我使用的是实例里的xingye-3图片
![1](https://user-images.githubusercontent.com/32833890/62184618-6e14d680-b391-11e9-8068-4b86d134c721.png)

**Comment by SunHu1** [comment]
修改了minNeighbors参数以后可以成功检测多张人脸图片
