### ISSUE TITLE
本是开源社区，看见你的打赏二维码，感觉你拉低了国内的开源精神，去看看国外的吧，没有这样的

### ISSUE THREAD

**Issue by iLucky7** [vipstone/faceai#53]

**Comment by roachsinai** [comment]
打赏二维码很正常。你觉得别人的开源不值得就不打赏就好了。`请我喝杯咖啡`明显就是国外的说法。而且Github官方也支持这种行为：https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository

看下面这个图片，国外的开发者反倒是养成了主动提出请你喝一杯咖啡的行为：

![image](https://user-images.githubusercontent.com/9500049/85811825-a4212d00-b791-11ea-821e-51109475d793.png)

https://github.com/Yggdroot/LeaderF/issues/360

到你这里不能反过来啊兄弟。

人家开源都是用的自己的时间，你从人家这里得到了帮助，一杯咖啡就可以了还不用你搭人情，这不过分啊。

其实，你说的`没有这样的`不是事实，你能做到的对开源的支持就是：或者帮助作者改进功能（issue,PR）或者打赏，不然就是白漂。当然人家既然开源就不怕你白漂，但是人家也相信会有人一起改进这个仓库的功能。

https://www.zhihu.com/question/325794991

**Comment by iLucky7** [comment]
1

**Comment by iLucky7** [comment]
2
