### ISSUE TITLE
请移除未授权的图片 Please remove unauthorized pictures

### ISSUE THREAD

**Issue by NearTan** [vipstone/faceai#6]
README 中使用了未授权的图片，请移除
There are unauthorized pictures in README file, please remove it.
<img width="531" alt="screen shot 2018-06-12 at 2 07 18 pm" src="https://user-images.githubusercontent.com/4445695/41273011-4238c52c-6e4a-11e8-8ab9-29edc48cbde5.png">

**Comment by archersmind** [comment]
@vipstone 可以考虑去 Unsplash 上找一些 sample 图片。
https://unsplash.com/license

**Comment by vipstone** [comment]
@NearTan 抱歉，给你造成了不便，我晚上处理一下。

**Comment by vipstone** [comment]
@archersmind 谢谢您的建议

**Comment by NearTan** [comment]
@vipstone 我不是照片上的姑娘啦，我只是在微博上看到然后过来提醒一下而已😄
